[supabase]
url = "https://rbvjopoltkzrtpfkfqtv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidmpvcG9sdGt6cnRwZmtmcXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTg3MjQsImV4cCI6MjA2Mjc5NDcyNH0.70wvJkvr32l7C-AYmE7v4CHqe34Z8X5au8qbk1UjwR4"
